jritchieBugTracker/Models/CodeFirst/TicketAttachment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace jritchieBugTracker.Models.CodeFirst
{
    public class TicketAttachment
    {
        public int Id { get; set; }
        public int TicketId { get; set; }   
        public string Description { get; set; }
        public DateTimeOffset Created { get; set; }
        public string AuthorId { get; set; }
        public string FileUrl { get; set; }         // Used for file retrieval/display.

        public virtual Ticket Ticket { get; set; }
        public virtual ApplicationUser Author { get; set; }
    }
}

jritchieBugTracker/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using jritchieBugTracker.Models;
using jritchieBugTracker.Models.CodeFirst;
using Microsoft.AspNet.Identity;
using jritchieBugTracker.Models.Helpers;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Configuration;

namespace jritchieBugTracker.Controllers
{
    [RequireHttps]
    public class TicketsController : UniversalController
    {
        // GET: Tickets
        [Authorize]
        public ActionResult Index()
        {
            //var tickets = db.Tickets.ToList();
            //return View(tickets);

            //var tickets = db.Tickets.Include(t => t.AssignToUser).Include(t => t.OwnerUser).Include(t => t.Project).Include(t => t.TicketPriority).Include(t => t.TicketStatus).Include(t => t.TicketType);
            //return View(tickets.ToList());

            //*************************************************************************
            //var user = db.Users.Find(User.Identity.GetUserId());
            //if (User.IsInRole("Admin"))
            //{
            //    return View(db.Tickets.ToList());
            //}
            //if (User.IsInRole("ProjectManager"))
            //{
            //    return View(db.Tickets.Where(t => t.Project.Users.Any(u => u.Id == user.Id)).ToList());
            //}
            //if (User.IsInRole("Developer"))
            //{
            //    return View(db.Tickets.Where(t => t.AssignToUserId == user.Id).ToList());
            //}
            //if (User.IsInRole("Submitter"))
            //{
            //    return View(db.Tickets.Where(t => t.OwnerUserId == user.Id).ToList());
            //}
            //return View("NoTickets");

            //return RedirectToAction("Index", "Home");
            //return View();
            //*************************************************************************

            ViewBag.UserTimeZone = db.Users.Find(User.Identity.GetUserId()).TimeZone;

            List<Ticket> UsersTickets = new List<Ticket>();
            var user = db.Users.Find(User.Identity.GetUserId());
            if (User.IsInRole("Admin"))
            {
                return View(db.Tickets.ToList());
            }
            if (User.IsInRole("ProjectManager"))
            {
                UsersTickets.AddRange(db.Tickets.Where(t => t.Project.Users.Any(u => u.Id == user.Id)).ToList());
            }
            if (User.IsInRole("Developer"))
            {
                UsersTickets.AddRange(db.Tickets.Where(t => t.AssignToUserId == user.Id).ToList());
            }
            if (User.IsInRole("Submitter"))
            {
                UsersTickets.AddRange(db.Tickets.Where(t => t.OwnerUserId == user.Id).ToList());
            }

            if (UsersTickets.Count != 0)
            {
                return View(UsersTickets.Distinct());
            }

            return View("NoTickets");
        }

        // GET: Tickets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }

            var user = db.Users.Find(User.Identity.GetUserId());
            ViewBag.UserId = user.Id;
            if (user.Roles.Count == 0)
            {
                return View("NoTickets");
            }

            ViewBag.UserTimeZone = db.Users.Find(User.Identity.GetUserId()).TimeZone;

            if (User.IsInRole("Admin"))
            {
                return View(ticket);
            }
            else if (User.IsInRole("ProjectManager") && ticket.Project.Users.Any(u => u.Id == user.Id))
            {
                return View(ticket);
            }
            else if (ticket.AssignToUserId == user.Id || ticket.OwnerUserId == user.Id)
            {
                return View(ticket);
            }
            //return View(ticket);
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }


        // GET: Tickets/Create
        [Authorize(Roles = "Submitter")]
        public ActionResult Create()
        {
            // Restrict to only Projects to which a Submitter belongs.
            ProjectAssignHelper helper = new ProjectAssignHelper();
            var projects = helper.ListUserProjects(db.Users.Find(User.Identity.GetUserId()).Id);
            ViewBag.ProjectId = new SelectList(projects, "Id", "Title");
            //ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Title");

            ViewBag.AssignToUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.OwnerUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name");
            ViewBag.TicketStatusId = new SelectList(db.TicketStatuses, "Id", "Name");
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Submitter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Description,Created,Updated,ProjectId,TicketTypeId,TicketPriorityId,TicketStatusId,OwnerUserId,AssignToUserId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                ticket.OwnerUserId = user.Id;

                ticket.Created = DateTimeOffset.UtcNow;
                ticket.TicketStatusId = db.TicketStatuses.FirstOrDefault(t => t.Name == "Unassigned").Id;

                db.Tickets.Add(ticket);

                //*****************************************************************
                TicketHistory ticketHistory = new TicketHistory();
                ticketHistory.TicketId = ticket.Id;
                ticketHistory.Property = "Ticket Creation";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = "Ticket Created";
                ticketHistory.Created = DateTimeOffset.UtcNow;
                ticketHistory.AuthorId = User.Identity.GetUserId();
                ticketHistory.HistoricPriority = ticket.TicketPriorityId;
                ticketHistory.HistoricStatus = ticket.TicketStatusId;
                db.TicketHistories.Add(ticketHistory);
                db.SaveChanges();

                ticketHistory.Property = "Ticket Name";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = ticket.Title.ToString();
                ticketHistory.Created = DateTimeOffset.UtcNow;
                ticketHistory.AuthorId = User.Identity.GetUserId();
                ticketHistory.HistoricPriority = ticket.TicketPriorityId;
                ticketHistory.HistoricStatus = ticket.TicketStatusId;
                db.TicketHistories.Add(ticketHistory);
                db.SaveChanges();

                ticketHistory.Property = "Ticket Description";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = ticket.Description.ToString();
                ticketHistory.Created = DateTimeOffset.UtcNow;
                ticketHistory.AuthorId = User.Identity.GetUserId();
                ticketHistory.HistoricPriority = ticket.TicketPriorityId;
                ticketHistory.HistoricStatus = ticket.TicketStatusId;
                db.TicketHistories.Add(ticketHistory);
                db.SaveChanges();

                ticketHistory.Property = "Ticket's Project";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = db.Projects.FirstOrDefault(p => p.Id == ticket.ProjectId).Title;
                ticketHistory.Created = DateTimeOffset.UtcNow;
                ticketHistory.AuthorId = User.Identity.GetUserId();
                ticketHistory.HistoricPriority = ticket.TicketPriorityId;
                ticketHistory.HistoricStatus = ticket.TicketStatusId;
                db.TicketHistories.Add(ticketHistory);
                db.SaveChanges();

                ticketHistory.Property = "Ticket Type";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = db.TicketTypes.FirstOrDefault(t => t.Id == ticket.TicketTypeId).Name;
                ticketHistory.Created = DateTimeOffset.UtcNow;
                ticketHistory.AuthorId = User.Identity.GetUserId();
                ticketHistory.HistoricPriority = ticket.TicketPriorityId;
                ticketHistory.HistoricStatus = ticket.TicketStatusId;
                db.TicketHistories.Add(ticketHistory);
                db.SaveChanges();

                ticketHistory.Property = "Ticket Priority";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = db.TicketPriorities.FirstOrDefault(t => t.Id == ticket.TicketPriorityId).Name;
                ticketHistory.Created = DateTimeOffset.UtcNow;
                ticketHistory.AuthorId = User.Identity.GetUserId();
                ticketHistory.HistoricPriority = ticket.TicketPriorityId;
                ticketHistory.HistoricStatus = ticket.TicketStatusId;
                db.TicketHistories.Add(ticketHistory);
                db.SaveChanges();

                ticketHistory.Property = "Ticket Status";
                ticketHistory.OldValue = "-";
                ticketHistory.NewValue = db.TicketStatuses.FirstOrDefault(t => t.Id == ticket.TicketStatusId).Name;
                ticketHistory.Created = DateTimeOffset.UtcNow;

jritchieBugTracker/Views/TicketAttachments/Create.cshtml
@model jritchieBugTracker.Models.CodeFirst.TicketAttachment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TicketAttachment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

jritchieBugTracker/Views/TicketAttachments/Delete.cshtml
@model jritchieBugTracker.Models.CodeFirst.TicketAttachment

@{
    ViewBag.Title = "Delete";
}

@*<h2>Delete</h2>*@
<div class="container">

    <div class="row" style="margin-top:10px">
        <div class="col-sm-12">
            <div class="card-box table-responsive">

                <h4 class="header-title m-t-0 m-b-30">Delete Attachment</h4>

                <hr />

                <h5 style="margin-bottom:20px">Are you sure you want to delete this?</h5>

                <div class="form-horizontal">
                    <div class="row">
                        <dl class="dl-horizontal">
                            <dt>
                                Ticket Name
                                @*@Html.DisplayNameFor(model => model.Ticket.Title)*@
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Ticket.Title)
                            </dd>

                            <dt>
                                File uploaded by
                                @*@Html.DisplayNameFor(model => model.Author.FirstName)*@
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Author.Fullname)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Created)
                            </dt>

                            <dd>
                                @Html.ToUserTime(Model.Created, ViewBag.UserTimeZone as string, "MM/dd/yyyy | hh:mm:ss")
                            </dd>

                            <dt>
                                File Name
                                @*@Html.DisplayNameFor(model => model.FileUrl)*@
                            </dt>

                            <dd>
                                <a href="@Model.FileUrl" target="_blank">@Model.FileUrl.Substring(Model.FileUrl.LastIndexOf("/") + 1)</a>
                                @*@Html.DisplayFor(model => model.FileUrl)*@
                            </dd>

                            <dt>
                                File Description
                                @*@Html.DisplayNameFor(model => model.Description)*@
                            </dt>

                            <dd>
                                @{
                                    if (Model.Description == null)
                                    {
                                        <span>-</span>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(model => model.Description)

                                    }
                                }
                            </dd>
                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color col-md-2">
                                <input type="submit" value="Delete" class="btn btn-default" />
                            </div>
                        }
                    </div>

                    <hr />

                    <div class="row" style="text-align:center">
                        <a href="@Url.Action("Details", "Tickets", new { id = Model.TicketId } )"><i class="fa fa-eye"></i><span> Return to Ticket Details </span></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

jritchieBugTracker/Views/TicketAttachments/Details.cshtml
@model jritchieBugTracker.Models.CodeFirst.TicketAttachment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TicketAttachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

jritchieBugTracker/Views/TicketAttachments/Edit.cshtml
@model jritchieBugTracker.Models.CodeFirst.TicketAttachment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TicketAttachment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TicketId)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.AuthorId)

        @*<div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>*@


        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <!-- -->
        <div class="form-group">
            <label class="control-label col-md-2">Replace existing attachment</label>
            <div class="col-md-10">
                <input name="attachment" type="file" class="form-control" />
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">File description</label>
            <div class="col-md-10">
                <input id="editor" class="form-control" name="Description" rows="1">
            </div>
        </div>*@
        <!-- -->

        <div class="form-group">
            <label class="control-label col-md-2">File description</label>
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

jritchieBugTracker/Views/TicketAttachments/Index.cshtml
@model IEnumerable<jritchieBugTracker.Models.CodeFirst.TicketAttachment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Author.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>